/*
 * generated by Xtext
 */
package uom.ac.uk.msc.cucumber;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class GherkinUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return uom.ac.uk.msc.cucumber.ui.internal.GherkinActivator.getInstance().getInjector("uom.ac.uk.msc.cucumber.Gherkin");
	}
	
}
