/*
 * generated by Xtext
 */
package uom.ac.uk.msc.cucumber.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GherkinUiModule extends
		uom.ac.uk.msc.cucumber.ui.AbstractGherkinUiModule {
	public GherkinUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	// public Class<? extends ITextEditComposer> bindITextEditComposer() {
	// System.out.println("### bindITextEditComposer");
	// return GherkinTextEditComposer.class;
	// }

	// public Class<? extends XtextDocumentProvider> bindXTextEditComposer() {
	// return GherkinDocumentProvider.class;
	// }
}
