/**
 * generated by Xtext
 */
package uom.ac.uk.msc.cucumber.formatting;

import javax.inject.Inject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;
import org.eclipse.xtext.xbase.lib.Extension;
import uom.ac.uk.msc.cucumber.services.GherkinGrammarAccess;

/**
 * This class contains custom formatting declarations.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#formatting
 * on how and when to use it.
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an example
 */
@SuppressWarnings("all")
public class GherkinFormatter extends AbstractDeclarativeFormatter {
  @Inject
  @Extension
  private GherkinGrammarAccess _gherkinGrammarAccess;
  
  @Override
  protected void configureFormatting(final FormattingConfig c) {
    FormattingConfig.LinewrapLocator _setLinewrap = c.setLinewrap(0, 1, 2);
    TerminalRule _sL_COMMENTRule = this._gherkinGrammarAccess.getSL_COMMENTRule();
    _setLinewrap.before(_sL_COMMENTRule);
    FormattingConfig.LinewrapLocator _setLinewrap_1 = c.setLinewrap(0, 1, 2);
    TerminalRule _mL_COMMENTRule = this._gherkinGrammarAccess.getML_COMMENTRule();
    _setLinewrap_1.before(_mL_COMMENTRule);
    FormattingConfig.LinewrapLocator _setLinewrap_2 = c.setLinewrap(0, 1, 1);
    TerminalRule _mL_COMMENTRule_1 = this._gherkinGrammarAccess.getML_COMMENTRule();
    _setLinewrap_2.after(_mL_COMMENTRule_1);
    IGrammarAccess _grammarAccess = super.getGrammarAccess();
    GherkinGrammarAccess access = ((GherkinGrammarAccess) ((GherkinGrammarAccess) _grammarAccess));
    FormattingConfig.IndentationLocatorStart _setIndentationIncrement = c.setIndentationIncrement();
    ParserRule _featureRule = access.getFeatureRule();
    _setIndentationIncrement.before(_featureRule);
    FormattingConfig.IndentationLocatorEnd _setIndentationDecrement = c.setIndentationDecrement();
    ParserRule _featureRule_1 = access.getFeatureRule();
    _setIndentationDecrement.after(_featureRule_1);
    FormattingConfig.IndentationLocatorStart _setIndentationIncrement_1 = c.setIndentationIncrement();
    ParserRule _backgroundRule = access.getBackgroundRule();
    _setIndentationIncrement_1.before(_backgroundRule);
    FormattingConfig.IndentationLocatorEnd _setIndentationDecrement_1 = c.setIndentationDecrement();
    ParserRule _backgroundRule_1 = access.getBackgroundRule();
    _setIndentationDecrement_1.after(_backgroundRule_1);
    FormattingConfig.IndentationLocatorStart _setIndentationIncrement_2 = c.setIndentationIncrement();
    ParserRule _scenarioRule = access.getScenarioRule();
    _setIndentationIncrement_2.before(_scenarioRule);
    FormattingConfig.IndentationLocatorEnd _setIndentationDecrement_2 = c.setIndentationDecrement();
    ParserRule _scenarioRule_1 = access.getScenarioRule();
    _setIndentationDecrement_2.after(_scenarioRule_1);
    FormattingConfig.IndentationLocatorStart _setIndentationIncrement_3 = c.setIndentationIncrement();
    ParserRule _scenarioOutlineRule = access.getScenarioOutlineRule();
    _setIndentationIncrement_3.before(_scenarioOutlineRule);
    FormattingConfig.IndentationLocatorEnd _setIndentationDecrement_3 = c.setIndentationDecrement();
    ParserRule _scenarioOutlineRule_1 = access.getScenarioOutlineRule();
    _setIndentationDecrement_3.after(_scenarioOutlineRule_1);
    FormattingConfig.IndentationLocatorStart _setIndentationIncrement_4 = c.setIndentationIncrement();
    ParserRule _narrativeRule = access.getNarrativeRule();
    _setIndentationIncrement_4.before(_narrativeRule);
    FormattingConfig.IndentationLocatorEnd _setIndentationDecrement_4 = c.setIndentationDecrement();
    ParserRule _narrativeRule_1 = access.getNarrativeRule();
    _setIndentationDecrement_4.after(_narrativeRule_1);
    FormattingConfig.IndentationLocatorStart _setIndentationIncrement_5 = c.setIndentationIncrement();
    ParserRule _stepRule = access.getStepRule();
    _setIndentationIncrement_5.before(_stepRule);
    FormattingConfig.IndentationLocatorEnd _setIndentationDecrement_5 = c.setIndentationDecrement();
    ParserRule _stepRule_1 = access.getStepRule();
    _setIndentationDecrement_5.after(_stepRule_1);
    FormattingConfig.NoSpaceLocator _setNoSpace = c.setNoSpace();
    ParserRule _stepKeywordRule = access.getStepKeywordRule();
    _setNoSpace.after(_stepKeywordRule);
    FormattingConfig.IndentationLocatorStart _setIndentationIncrement_6 = c.setIndentationIncrement();
    ParserRule _examplesRule = access.getExamplesRule();
    _setIndentationIncrement_6.before(_examplesRule);
    FormattingConfig.IndentationLocatorEnd _setIndentationDecrement_6 = c.setIndentationDecrement();
    ParserRule _examplesRule_1 = access.getExamplesRule();
    _setIndentationDecrement_6.after(_examplesRule_1);
    FormattingConfig.IndentationLocatorStart _setIndentationIncrement_7 = c.setIndentationIncrement();
    ParserRule _tableRule = access.getTableRule();
    _setIndentationIncrement_7.before(_tableRule);
    FormattingConfig.IndentationLocatorEnd _setIndentationDecrement_7 = c.setIndentationDecrement();
    ParserRule _tableRule_1 = access.getTableRule();
    _setIndentationDecrement_7.after(_tableRule_1);
    FormattingConfig.IndentationLocatorStart _setIndentationIncrement_8 = c.setIndentationIncrement();
    ParserRule _docStringRule = access.getDocStringRule();
    _setIndentationIncrement_8.before(_docStringRule);
    FormattingConfig.IndentationLocatorEnd _setIndentationDecrement_8 = c.setIndentationDecrement();
    ParserRule _docStringRule_1 = access.getDocStringRule();
    _setIndentationDecrement_8.after(_docStringRule_1);
  }
}
