/**
 * generated by Xtext
 */
package uom.ac.uk.msc.cucumber.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class GherkinLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public GherkinLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
}
