/**
 * generated by Xtext
 */
package uom.ac.uk.msc.cucumber.ui.contentassist;

import uom.ac.uk.msc.cucumber.ui.contentassist.AbstractGherkinProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class GherkinProposalProvider extends AbstractGherkinProposalProvider {
}
