/*
 * generated by Xtext
 */
package uom.ac.uk.msc.cucumber.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractGherkinValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(uom.ac.uk.msc.cucumber.gherkin.GherkinPackage.eINSTANCE);
		return result;
	}
}
