/*
 * generated by Xtext
 */
package uom.ac.uk.msc.cucumber;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class GherkinStandaloneSetup extends GherkinStandaloneSetupGenerated{

	public static void doSetup() {
		new GherkinStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

