/*
 * generated by Xtext
 */
package uom.ac.uk.msc.cucumber;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class GherkinRuntimeModule extends
		uom.ac.uk.msc.cucumber.AbstractGherkinRuntimeModule {
}
