/*
 * generated by Xtext
 */
package uom.ac.uk.msc.cucumber.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import uom.ac.uk.msc.cucumber.services.GherkinGrammarAccess;

@SuppressWarnings("all")
public class GherkinSyntacticSequencer extends AbstractSyntacticSequencer {

	protected GherkinGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Background_EOLTerminalRuleCall_2_p;
	protected AbstractElementAlias match_DocString_EOLTerminalRuleCall_1_a;
	protected AbstractElementAlias match_Examples_EOLTerminalRuleCall_2_p;
	protected AbstractElementAlias match_Feature_EOLTerminalRuleCall_3_p;
	protected AbstractElementAlias match_ScenarioOutline_EOLTerminalRuleCall_3_p;
	protected AbstractElementAlias match_Scenario_EOLTerminalRuleCall_3_p;
	protected AbstractElementAlias match_Step_EOLTerminalRuleCall_2_a;
	protected AbstractElementAlias match_Table_EOLTerminalRuleCall_1_a;
	protected AbstractElementAlias match_Tag_EOLTerminalRuleCall_1_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (GherkinGrammarAccess) access;
		match_Background_EOLTerminalRuleCall_2_p = new TokenAlias(true, false, grammarAccess.getBackgroundAccess().getEOLTerminalRuleCall_2());
		match_DocString_EOLTerminalRuleCall_1_a = new TokenAlias(true, true, grammarAccess.getDocStringAccess().getEOLTerminalRuleCall_1());
		match_Examples_EOLTerminalRuleCall_2_p = new TokenAlias(true, false, grammarAccess.getExamplesAccess().getEOLTerminalRuleCall_2());
		match_Feature_EOLTerminalRuleCall_3_p = new TokenAlias(true, false, grammarAccess.getFeatureAccess().getEOLTerminalRuleCall_3());
		match_ScenarioOutline_EOLTerminalRuleCall_3_p = new TokenAlias(true, false, grammarAccess.getScenarioOutlineAccess().getEOLTerminalRuleCall_3());
		match_Scenario_EOLTerminalRuleCall_3_p = new TokenAlias(true, false, grammarAccess.getScenarioAccess().getEOLTerminalRuleCall_3());
		match_Step_EOLTerminalRuleCall_2_a = new TokenAlias(true, true, grammarAccess.getStepAccess().getEOLTerminalRuleCall_2());
		match_Table_EOLTerminalRuleCall_1_a = new TokenAlias(true, true, grammarAccess.getTableAccess().getEOLTerminalRuleCall_1());
		match_Tag_EOLTerminalRuleCall_1_q = new TokenAlias(false, true, grammarAccess.getTagAccess().getEOLTerminalRuleCall_1());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if(ruleCall.getRule() == grammarAccess.getEOLRule())
			return getEOLToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * terminal EOL: NL;
	 */
	protected String getEOLToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if(match_Background_EOLTerminalRuleCall_2_p.equals(syntax))
				emit_Background_EOLTerminalRuleCall_2_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_DocString_EOLTerminalRuleCall_1_a.equals(syntax))
				emit_DocString_EOLTerminalRuleCall_1_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Examples_EOLTerminalRuleCall_2_p.equals(syntax))
				emit_Examples_EOLTerminalRuleCall_2_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Feature_EOLTerminalRuleCall_3_p.equals(syntax))
				emit_Feature_EOLTerminalRuleCall_3_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_ScenarioOutline_EOLTerminalRuleCall_3_p.equals(syntax))
				emit_ScenarioOutline_EOLTerminalRuleCall_3_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Scenario_EOLTerminalRuleCall_3_p.equals(syntax))
				emit_Scenario_EOLTerminalRuleCall_3_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Step_EOLTerminalRuleCall_2_a.equals(syntax))
				emit_Step_EOLTerminalRuleCall_2_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Table_EOLTerminalRuleCall_1_a.equals(syntax))
				emit_Table_EOLTerminalRuleCall_1_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Tag_EOLTerminalRuleCall_1_q.equals(syntax))
				emit_Tag_EOLTerminalRuleCall_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     EOL+
	 *
	 * This ambiguous syntax occurs at:
	 *     backgroundKeyword=BackgroundKeyword (ambiguity) narrative=Narrative
	 *     backgroundKeyword=BackgroundKeyword (ambiguity) steps+=Step
	 *     title=Title (ambiguity) narrative=Narrative
	 *     title=Title (ambiguity) steps+=Step
	 */
	protected void emit_Background_EOLTerminalRuleCall_2_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     EOL*
	 *
	 * This ambiguous syntax occurs at:
	 *     content=DOC_STRING (ambiguity) (rule end)
	 */
	protected void emit_DocString_EOLTerminalRuleCall_1_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     EOL+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'Examples:' (ambiguity) narrative=Narrative
	 *     (rule start) 'Examples:' (ambiguity) table=Table
	 *     title=Title (ambiguity) narrative=Narrative
	 *     title=Title (ambiguity) table=Table
	 */
	protected void emit_Examples_EOLTerminalRuleCall_2_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     EOL+
	 *
	 * This ambiguous syntax occurs at:
	 *     title=Title (ambiguity) background=Background
	 *     title=Title (ambiguity) narrative=Narrative
	 *     title=Title (ambiguity) scenarios+=Scenario
	 *     title=Title (ambiguity) scenarios+=ScenarioOutline
	 */
	protected void emit_Feature_EOLTerminalRuleCall_3_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     EOL+
	 *
	 * This ambiguous syntax occurs at:
	 *     title=Title (ambiguity) narrative=Narrative
	 *     title=Title (ambiguity) steps+=Step
	 */
	protected void emit_ScenarioOutline_EOLTerminalRuleCall_3_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     EOL+
	 *
	 * This ambiguous syntax occurs at:
	 *     title=Title (ambiguity) narrative=Narrative
	 *     title=Title (ambiguity) steps+=Step
	 */
	protected void emit_Scenario_EOLTerminalRuleCall_3_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     EOL*
	 *
	 * This ambiguous syntax occurs at:
	 *     description=StepDescription (ambiguity) (rule end)
	 *     description=StepDescription (ambiguity) code=DocString
	 *     description=StepDescription (ambiguity) tables+=Table
	 */
	protected void emit_Step_EOLTerminalRuleCall_2_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     EOL*
	 *
	 * This ambiguous syntax occurs at:
	 *     rows+=TABLE_ROW (ambiguity) (rule end)
	 */
	protected void emit_Table_EOLTerminalRuleCall_1_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     EOL?
	 *
	 * This ambiguous syntax occurs at:
	 *     id=TAGNAME (ambiguity) (rule end)
	 */
	protected void emit_Tag_EOLTerminalRuleCall_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
